### ISSUE TITLE
Client fails frequently inside 'rubrik_node_stats.go'

### ISSUE THREAD

**Issue by ZeFrenchBibster** [rubrikinc/rubrik-client-for-prometheus#16]
**Expected Behavior**

the client just keeps running

**Current Behavior**

Client fails frequently inside 'rubrik_node_stats.go'

**Failure Information (for bugs)**
See below

* Use verbose outputs to capture any debug information.
```
2021/02/25 10:20:02 Cluster name: blmrub01
2021/02/25 10:20:02 Starting on HTTP port 8080
2021/02/25 11:16:01 Error from stats.GetNodeStats:  Unable to establish a connection to the Rubrik cluster
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 14 [running]:
github.com/rubrikinc/rubrik-client-for-prometheus/src/golang/stats.GetNodeStats(0xc000172080, 0xc000028dc0, 0x8)
	/root/go/src/github.com/rubrikinc/rubrik-client-for-prometheus/src/golang/stats/rubrik_node_stats.go:86 +0xdf2
main.main.func2(0xc000172080, 0x8e8360, 0xc00001f760)
	/root/Rubrik/20210224/rubrik-client-for-prometheus/src/golang/main.go:60 +0x43
created by main.main
	/root/Rubrik/20210224/rubrik-client-for-prometheus/src/golang/main.go:58 +0x249
```

**Steps to Reproduce**

Restart the client, wait a bit, and it breaks again... had to set the container to --restart always

**Context**

Cloned the repo yesterday, to try to get around the problem, but alas.

Rubrik Cluster has been upgraded yesterday to 5.3.0-p2-18423

**Failure Logs**

See above.

**Comment by ZeFrenchBibster** [comment]
Happens in other modules as well, by the way... I've had the 'spray server' restarted as well... in vain
